before:
  hooks:
    - go mod download
builds:
  - id: "porter-cli"
    binary: porter
    env:
      - CGO_ENABLED=1
    dir: cli
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=cli
    hooks:
      post: gon gon.hcl
archives:
  - format: binary
    replacements:
      darwin: Darwin
release:
  disable: true
checksum:
  disable: true
changelog:
  skip: true