before:
  hooks:
    - go mod download
builds:
  - id: "porter-cli"
    binary: porter
    ldflags:
    - -X 'github.com/porter-dev/porter/cli/cmd.Version={{.Version}}'
    env:
      - CGO_ENABLED=1
    dir: cli
    main: ./main.go
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -tags=cli
    hooks:
      post: gon gon.cli.hcl
  # - id: "porter-server"
  #   binary: portersvr
  #   env:
  #     - CGO_ENABLED=1
  #   dir: cmd/app
  #   main: ./main.go
  #   goos:
  #     - darwin
  #   goarch:
  #     - amd64
  #   hooks:
  #     post: gon gon.server.hcl
archives:
  - format: binary
    replacements:
      darwin: Darwin
release:
  disable: true
checksum:
  disable: true
changelog:
  skip: true