before:
  hooks:
    - go mod download
builds:
  # - id: "porter-cli"
  #   binary: porter
  #   env:
  #     - CGO_ENABLED=1
  #   dir: cli
  #   main: ./main.go
  #   goos:
  #     - linux
  #     - windows
  #   goarch:
  #     - amd64
  #   flags:
  #     - -tags=cli
  - id: "porter-server"
    binary: portersvr
    env:
      - CGO_ENABLED=1
    dir: cmd/app
    main: ./main.go
    goos:
      - linux
      - windows
    goarch:
      - amd64
archives:
  - format: zip
    replacements:
      linux: Linux
      windows: Windows
      amd64: x86_64
release:
  disable: true
# checksum:
#   disable: true
changelog:
  skip: true
