version: '3'
services:
  porter:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: on-failure
    volumes:
      - ./:/porter

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=porter
      - POSTGRES_PASSWORD=porter
      - POSTGRES_DB=porter
    ports:
      - 5400:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: