version: '3'
services:
  webpack:
    build:
      context: ./dashboard
      dockerfile: ./docker/dev.Dockerfile
    restart: on-failure
    volumes:
      - ./dashboard:/webpack:rw,cached
      - /webpack/node_modules
  porter:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./docker/.env
    command: /bin/sh -c '/porter/bin/migrate; air -c .air.toml;'
    restart: on-failure
    volumes:
      - ./cmd:/porter/cmd
      - ./internal:/porter/internal
      - ./server:/porter/server
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=porter
      - POSTGRES_PASSWORD=porter
      - POSTGRES_DB=porter
    ports:
      - 5400:5432
    volumes:
      - database:/var/lib/postgresql/data
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - ./docker/nginx_local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - porter
      - webpack    

volumes:
  database:
  metabase: