version: '3'
services:
  porter:
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    env_file:
      - ./docker/.env
    command: /bin/sh -c '/porter/bin/migrate; air -c .air.toml;'
    restart: on-failure
    volumes:
      - ./cmd:/porter/cmd
      - ./internal:/porter/internal
      - ./server:/porter/server

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=porter
      - POSTGRES_PASSWORD=porter
      - POSTGRES_DB=porter
    ports:
      - 5400:5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: