apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2021-01-02T01:14:37Z","generation":1,"labels":{"app":"porter-prov"},"name":"porter-prov-test","namespace":"default","resourceVersion":"56617370","selfLink":"/apis/apps/v1/namespaces/default/deployments/porter-prov-test","uid":"e0d6b580-3dd5-48c4-bf7f-1667b3b71d04"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"porter-prov"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"porter-prov"}},"spec":{"containers":[{"env":[{"name":"DB_HOST","value":"postgres-postgresql.default.svc.cluster.local"},{"name":"DB_PORT","value":"5432"},{"name":"DB_USER","value":"postgres"},{"name":"DB_PASS","valueFrom":{"secretKeyRef":{"key":"postgresql-password","name":"postgres-postgresql"}}},{"name":"REDIS_HOST","value":"redis-master.default.svc.cluster.local"},{"name":"REDIS_USER","value":"default"},{"name":"REDIS_PASS","valueFrom":{"secretKeyRef":{"key":"redis-password","name":"redis"}}}],"image":"gcr.io/porter-dev-273614/porter-prov:latest","imagePullPolicy":"Always","name":"porter-prov","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{"requests":{"cpu":"1000m","memory":"2000Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2021-01-02T01:14:37Z","lastUpdateTime":"2021-01-02T01:14:42Z","message":"ReplicaSet \"porter-prov-test-7cbd4d464\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2021-01-05T04:11:30Z","lastUpdateTime":"2021-01-05T04:11:30Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":1,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2021-01-02T01:14:37Z"
  generation: 2
  labels:
    app: porter-prov
  name: porter-prov-test
  namespace: default
  resourceVersion: "57433465"
  selfLink: /apis/apps/v1/namespaces/default/deployments/porter-prov-test
  uid: e0d6b580-3dd5-48c4-bf7f-1667b3b71d04
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: porter-prov
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: porter-prov
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: postgres-postgresql.default.svc.cluster.local
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: postgres-postgresql
        - name: REDIS_HOST
          value: redis-master.default.svc.cluster.local
        - name: REDIS_USER
          value: default
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              key: redis-password
              name: redis
        image: gcr.io/porter-dev-273614/porter-prov:latest
        imagePullPolicy: Always
        name: porter-prov
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: 3000Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-05T04:11:30Z"
    lastUpdateTime: "2021-01-05T04:11:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-02T01:14:37Z"
    lastUpdateTime: "2021-01-06T17:59:17Z"
    message: ReplicaSet "porter-prov-test-6774488fcb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
