name: Build, Push to GCR.
on:
  push:
    branches:
    - staging
jobs:
  build-push-test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Log in to gcloud CLI
      run: gcloud auth configure-docker
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Build
      run: |
        docker build . -t gcr.io/porter-dev-273614/porter-prov:latest -f ./docker/Dockerfile
        docker push gcr.io/porter-dev-273614/porter-prov:latest
